"""
Default configuration file for RadCLss

This file contains default parameters and variables used throughout RadCLss.

"""
# Define variables to drop from RadCLss from the respective datastreams 
DEFAULT_DISCARD_VAR = {'radar' : ['classification_mask',
                            'censor_mask',
                            'uncorrected_copol_correlation_coeff',
                            'uncorrected_differential_phase',
                            'uncorrected_differential_reflectivity',
                            'uncorrected_differential_reflectivity_lag_1',
                            'uncorrected_mean_doppler_velocity_h',
                            'uncorrected_mean_doppler_velocity_v',
                            'uncorrected_reflectivity_h',
                            'uncorrected_reflectivity_v',
                            'uncorrected_spectral_width_h',
                            'uncorrected_spectral_width_v',
                            'clutter_masked_velocity',
                            'gate_id',
                            'ground_clutter',
                            'partial_beam_blockage',
                            'cumulative_beam_blockage',
                            'unfolded_differential_phase',
                            'path_integrated_attenuation',
                            'path_integrated_differential_attenuation',
                            'unthresholded_power_copolar_v',
                            'unthresholded_power_copolar_h',
                            'specific_differential_phase',
                            'specific_differential_attenuation',
                            'reflectivity_v',
                            'reflectivity',
                            'mean_doppler_velocity_v',
                            'mean_doppler_velocity',
                            'differential_reflectivity_lag_1',
                            'differential_reflectivity',
                            'differential_phase',
                            'normalized_coherent_power',
                            'normalized_coherent_power_v',
                            'signal_to_noise_ratio_copolar_h',
                            'signal_to_noise_ratio_copolar_v',
                            'specific_attenuation',
                            'spectral_width',
                            'spectral_width_v',
                            'sounding_temperature',
                            'signal_to_noise_ratio',
                            'velocity_texture',
                            'simulated_velocity',
                            'height_over_iso0'
                    ],
                    'met' : ['base_time', 'time_offset', 'time_bounds', 'logger_volt',
                        'logger_temp', 'qc_logger_temp', 'lat', 'lon', 'alt', 'qc_temp_mean',
                        'qc_rh_mean', 'qc_vapor_pressure_mean', 'qc_wspd_arith_mean', 'qc_wspd_vec_mean',
                        'qc_wdir_vec_mean', 'qc_pwd_mean_vis_1min', 'qc_pwd_mean_vis_10min', 'qc_pwd_pw_code_inst',
                        'qc_pwd_pw_code_15min', 'qc_pwd_pw_code_1hr', 'qc_pwd_precip_rate_mean_1min',
                        'qc_pwd_cumul_rain', 'qc_pwd_cumul_snow', 'qc_org_precip_rate_mean', 'qc_tbrg_precip_total',
                        'qc_tbrg_precip_total_corr', 'qc_logger_volt', 'qc_logger_temp', 'qc_atmos_pressure', 
                        'pwd_pw_code_inst', 'pwd_pw_code_15min', 'pwd_pw_code_1hr', 'temp_std', 'rh_std',
                        'vapor_pressure_std', 'wdir_vec_std', 'tbrg_precip_total', 'org_precip_rate_mean',
                        'pwd_mean_vis_1min', 'pwd_mean_vis_10min', 'pwd_precip_rate_mean_1min', 'pwd_cumul_rain',
                        'pwd_cumul_snow', 'pwd_err_code'
                    ],
                    'sonde' : ['base_time', 'time_offset', 'lat', 'lon', 'qc_pres',
                            'qc_tdry', 'qc_dp', 'qc_wspd', 'qc_deg', 'qc_rh',
                            'qc_u_wind', 'qc_v_wind', 'qc_asc', "wstat", "asc"
                    ],
                    'pluvio' : ['base_time', 'time_offset', 'load_cell_temp', 'heater_status',
                            'elec_unit_temp', 'supply_volts', 'orifice_temp', 'volt_min',
                            'ptemp', 'lat', 'lon', 'alt', 'maintenance_flag', 'reset_flag', 
                            'qc_rh_mean', 'pluvio_status', 'bucket_rt', 'accum_total_nrt'
                    ],
                    'ldquants' : ['specific_differential_attenuation_xband20c',
                                'specific_differential_attenuation_kaband20c',
                                'specific_differential_attenuation_sband20c',
                                'bringi_conv_stra_flag',
                                'exppsd_slope',
                                'norm_num_concen',
                                'num_concen',
                                'gammapsd_shape',
                                'gammapsd_slope',
                                'mean_doppler_vel_wband20c',
                                'mean_doppler_vel_kaband20c',
                                'mean_doppler_vel_xband20c',
                                'mean_doppler_vel_sband20c',
                                'specific_attenuation_kaband20c',
                                'specific_attenuation_xband20c',
                                'specific_attenuation_sband20c',
                                'specific_differential_phase_kaband20c',
                                'specific_differential_phase_xband20c',
                                'specific_differential_phase_sband20c',
                                'differential_reflectivity_kaband20c',
                                'differential_reflectivity_xband20c',
                                'differential_reflectivity_sband20c',
                                'reflectivity_factor_wband20c',
                                'reflectivity_factor_kaband20c',
                                'reflectivity_factor_xband20c',
                                'reflectivity_factor_sband20c',
                                'bringi_conv_stra_flag',
                                'time_offset',
                                'base_time',
                                'lat',
                                'lon',
                                'alt'
                    ],
                    'vdisquants' : ['specific_differential_attenuation_xband20c',
                                'specific_differential_attenuation_kaband20c',
                                'specific_differential_attenuation_sband20c',
                                'bringi_conv_stra_flag',
                                'exppsd_slope',
                                'norm_num_concen',
                                'num_concen',
                                'gammapsd_shape',
                                'gammapsd_slope',
                                'mean_doppler_vel_wband20c',
                                'mean_doppler_vel_kaband20c',
                                'mean_doppler_vel_xband20c',
                                'mean_doppler_vel_sband20c',
                                'specific_attenuation_kaband20c',
                                'specific_attenuation_xband20c',
                                'specific_attenuation_sband20c',
                                'specific_differential_phase_kaband20c',
                                'specific_differential_phase_xband20c',
                                'specific_differential_phase_sband20c',
                                'differential_reflectivity_kaband20c',
                                'differential_reflectivity_xband20c',
                                'differential_reflectivity_sband20c',
                                'reflectivity_factor_wband20c',
                                'reflectivity_factor_kaband20c',
                                'reflectivity_factor_xband20c',
                                'reflectivity_factor_sband20c',
                                'bringi_conv_stra_flag',
                                'time_offset',
                                'base_time',
                                'lat',
                                'lon',
                                'alt'
                    ],
                    'wxt' : ['base_time',
                            'time_offset',
                            'time_bounds',
                            'qc_temp_mean',
                            'temp_std',
                            'rh_mean',
                            'qc_rh_mean',
                            'rh_std',
                            'atmos_pressure',
                            'qc_atmos_pressure',
                            'wspd_arith_mean',
                            'qc_wspd_arith_mean',
                            'wspd_vec_mean',
                            'qc_wspd_vec_mean',
                            'wdir_vec_mean',
                            'qc_wdir_vec_mean',
                            'wdir_vec_std',
                            'qc_wxt_precip_rate_mean',
                            'qc_wxt_cumul_precip',
                            'logger_volt',
                            'qc_logger_volt',
                            'logger_temp',
                            'qc_logger_temp',
                            'lat',
                            'lon',
                            'alt'
                    ]
    }



def set_discarded_variables(instrument, var_list):
    """
    Set the variables to be discarded from a given instrument datastream.

    Parameters
    ----------
    instrument : str
        The instrument name (e.g., 'radar', 'met', 'sonde', etc.).
    var_list : list
        List of variable names to discard.
    """
    global DEFAULT_DISCARD_VAR
    DEFAULT_DISCARD_VAR[instrument] = var_list