name: testenv
channels:
   - conda-forge
dependencies:
   - arm_pyart
   - pip
   - act-atmos
   - xradar
   - pytest
   - pytest-mpl
   - pytest-cov
   - matplotlib
   - dask
   - boto3
   - arm-test-data
   - distributed
   - xarray
   - pandas
   - numpy<=2.4.0
